### ISSUE TITLE
 Sub-Store开启局域网访问，能否直接给出可复制的局域网访问地址

### ISSUE THREAD

**Issue by Zhang-S-g** [mihomo-party-org/mihomo-party#246]
### Verify steps

- [X] 我已在标题简短的描述了我所需的功能
- [ ] 我已在[Issue Tracker](./?q=is%3Aissue)中寻找过,但未找到我所需的功能
- [ ] 这是向GUI程序提出的功能请求,而不是内核程序
- [ ] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

 Sub-Store开启局域网访问，能否直接给出可复制的局域网访问地址

**Comment by xishang0128** [comment]
sub store内置目的只是为了本地使用,局域网连接请自行寻找ip地址
