### ISSUE TITLE
垃圾软件

### ISSUE THREAD

**Issue by pompurin404** [mihomo-party-org/mihomo-party#266]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我已在 [Issue Tracker](./?q=is%3Aissue) 中找到我要提出的问题
- [X] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中找到我要提出的问题
- [X] 这是 GUI 程序的问题，而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

win11

### 发生问题 mihomo-party 版本

1.5.3

### 描述

软件太垃圾了，一点也不好用

### 重现方式

傻逼

**Comment by xishang0128** [comment]
该 issue 应被关闭，原因如下：1. 标题和内容使用了不当和冒犯性的语言，不符合礼貌和建设性的讨论要求。2. 虽然用户勾选了所有验证步骤，但实际内容并未提供任何有价值的信息或具体的问题描述。3. 描述和重现方式部分只包含了侮辱性词语，没有提供任何有助于解决问题的信息。4. 这种类型的反馈不利于项目的改进和发展，也不符合社区互助的精神。建议在关闭 issue 时，提醒用户遵守社区准则，并以建设性的方式提供反馈。
