### ISSUE TITLE
[Bug] 功能不生效

### ISSUE THREAD

**Issue by nekolsd** [mihomo-party-org/mihomo-party#273]
### Verify steps

- [X] 我已在标题简短的描述了我所遇到的问题
- [X] 我已在 [Issue Tracker](./?q=is%3Aissue) 中找到我要提出的问题
- [X] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中找到我要提出的问题
- [X] 这是 GUI 程序的问题，而不是内核程序的问题
- [X] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [X] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

MacOS

### 系统版本

15

### 发生问题 mihomo-party 版本

1.5.3

### 描述

软件打开之后并没有猫娘蹦出来哄我休息

### 重现方式

第一步：打开软件
第二步：开启内核设置
这里我就看不到任何关于猫娘的设置了。
众所周知猫娘是 mihomo 的重要内嵌功能，上个版本移除猫娘一键召唤功能之后严重影响了软件正常工作。

**Comment by pompurin404** [comment]
该 issue 的问题描述与项目相关性存疑，提到的“猫娘”功能并非软件的标准功能或文档中提到的功能。这导致了其内容偏离主题。此外，即使复选框已勾选，但其内容与复选框所描述的情况并不一致，因此根据关闭标准，该 issue 需要关闭。
