### ISSUE TITLE
[Feature] 希望可以增加隐藏右键菜单策略组的功能

### ISSUE THREAD

**Issue by chr1snolan** [mihomo-party-org/mihomo-party#418]
### Verify steps

- [x] 我已在标题简短的描述了我所需的功能
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过，但未找到我所需的功能
- [x] 这是向 GUI 程序提出的功能请求，而不是内核程序
- [x] 我未在最新的测试版本找到我所需的功能

### 操作系统

Windows

### 描述

![Image](https://github.com/user-attachments/assets/128b5eda-202a-4008-b5c6-0634dc4d5c90)
任务栏图标右键菜单能否增加一个隐藏策略组的功能？如果策略组比较多的话显示很不方便，菜单直接占满了整个屏幕

**Comment by carey-hu** [comment]
在设置里有托盘菜单显示节点信息选择，取消选择就好了。
